// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMPpxchW-nn_9RsetzD8Xb6NZzUw0b3ME',
    appId: '1:919661608404:web:1b94bfd33f093a71b3ea41',
    messagingSenderId: '919661608404',
    projectId: 'socialmedia-114a5',
    authDomain: 'socialmedia-114a5.firebaseapp.com',
    storageBucket: 'socialmedia-114a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAkNeHq5JfJ8SUPeG0_p4qXuWoTU0NIjE',
    appId: '1:919661608404:android:4d8e5987d423c0dbb3ea41',
    messagingSenderId: '919661608404',
    projectId: 'socialmedia-114a5',
    storageBucket: 'socialmedia-114a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrRmqMUbNL6vlaEFfHlQaQXaMbbGQW5rw',
    appId: '1:919661608404:ios:be673ce789e0281cb3ea41',
    messagingSenderId: '919661608404',
    projectId: 'socialmedia-114a5',
    storageBucket: 'socialmedia-114a5.appspot.com',
    iosClientId: '919661608404-pnfo90l0ch1aafidlabe3gj3ue2nsvfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrRmqMUbNL6vlaEFfHlQaQXaMbbGQW5rw',
    appId: '1:919661608404:ios:6b270f10a4a50fbab3ea41',
    messagingSenderId: '919661608404',
    projectId: 'socialmedia-114a5',
    storageBucket: 'socialmedia-114a5.appspot.com',
    iosClientId: '919661608404-sgmm63q71enq08njbdrcij7d0q6iihu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmedia.RunnerTests',
  );
}
